### ISSUE TITLE
Is there any prebuilt DLLs?

### ISSUE THREAD

**Issue by ghost** [gammasoft71/xtd_c#1]

**Comment by gammasoft71** [comment]
No, there is no prebuild DLL.
The project is currently on-hold, as the priority is to make as much progress as possible on the c++ version [xtd](https://github.com/gammasoft71/xtd).

**Comment by ghost** [comment]
> No, there is no prebuild DLL. The project is currently on-hold, as the priority is to make as much progress as possible on the c++ version [xtd](https://github.com/gammasoft71/xtd).

Please provide the DLL when the project is ready. Thank you.
